### ISSUE TITLE
🐛 매달 1일에 지출내역 등록을 하면 전의 달 1일로 지출내역이 추가됨

### ISSUE THREAD

**Issue by yanni13** [CollaBu/pennyway-client-ios#115]
## 버그 내용
datePicker랑 연동후에 7월 1일로 지출내역을 등록하니, 6월 1일에 지출내역이 등록되어 표시된다. 근데 로그를 찍어서 확인해보니 api 도 7월 1일로 정상적으로 지출등록이 되어 있고 선택한 날짜도 7월1일로 표시되어 있다. 그래서 6월 1일의 내역을 클릭해도 지출내역은 나오지 않고 금액만 나와있다. (나머지 날짜는 정상적으로 등록되는데, 달의 1일만 그럼)

![image](https://github.com/user-attachments/assets/55c8ea38-744a-4b97-9e77-2b3a7428d1a5)
지출내역 추가는 7월 1일로 되지만, 데이터 조회하는데서 문제가 발생한 거 같다.

## 버그 위치
`SpendingCalendarView`

## 재현
<img src ="https://github.com/user-attachments/assets/fe45806d-fbf7-43aa-9150-4794242c7e07" width ="300" height ="600">

## 할일
데이터 조회시 날짜 처리하는 부분에 대한 로직 찾아보기

**Comment by psychology50** [comment]
해당 이슈는 백엔드측 RDB timezone 설정이 잘못되어 발생한 이슈로 판단하여 조치했습니다.  
따라서 해당 이슈를 닫습니다.
