### ISSUE TITLE
📍 'openURL:', 'SFAuthenticationSession' is deprecated

### ISSUE THREAD

**Issue by heejinnn** [CollaBu/pennyway-client-ios#25]
## 버그 내용

저번에 말씀해주신 deprecated된 것에 대한 오류는 아래와 같았습니다.

![스크린샷 2024-04-07 오후 11 49 21](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/42cfb6db-ce57-4367-ab8e-1adeffe8fd36)

두 파일에서 오류가 났는데

- OIDExternalUserAgentIOS

<br/>

![스크린샷 2024-04-07 오후 11 51 46](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/4fc72d9c-dc93-4f94-9621-0d4d5c69ec45)

SFAuthenticationSession -> ASWebAuthenticationSession으로 바꿔주니 `'SFAuthenticationSession' is deprecated: first deprecated in iOS 12.0` 이 오류는 나오지 않았습니다

이제 문제가 여기 안에 있는 @available인데 iOS 9.0과 10.0인 경우 그리고 iOS 11인 경우 처리하는 로직에서 오류가 나더라고요.
저희 어차피 iOS 14가 타겟이니 12이상인 로직만 필요할 것 같아서 지우려고 하니 문제가 될까봐 조심스럽네요,,, 일단 지우고 oauth 로직 돌려보니 정상 처리되긴 하더라고요 

![스크린샷 2024-04-07 오후 11 53 27](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/5f41d058-a23d-448d-81ab-af68ae2f3c08)

![스크린샷 2024-04-08 오전 12 03 02](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/9bb4b392-3846-4b89-9322-400b36649f61)

https://github.com/Baseflow/flutter-geolocator/issues/955
이 링크 참고했습니다!

- OIDExternalUserAgentIOSCustomBrowser

여기서는 `openURL:`오류만 나더라고요

<br/>

1.
![스크린샷 2024-04-07 오후 11 59 54](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/9390156e-00c7-4e0c-b6d0-d849f50d3778)

<br/>

2.
![스크린샷 2024-04-08 오전 12 11 11](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/54c1f4ac-f398-47a9-93d1-5900a34b54fe)

그래서 다음과 같이 처리하니 해결했습니다!

<br/>

1. 
![스크린샷 2024-04-08 오전 12 00 16](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/2e7ef280-da77-4e56-850c-722fde81c65d)

<br/>

2. 
![스크린샷 2024-04-08 오전 12 13 53](https://github.com/CollaBu/pennyway-client-ios/assets/103185302/039e7855-7832-4a5c-8d40-74321caa5f33)

## 버그 위치

AppAuth 라이브러리 

## 할일

@available 부분 지워도 될까?

**Comment by yanni13** [comment]
https://github.com/openid/AppAuth-iOS/pull/246#issue-329684188 

찾아봤는데 ios 12 , xcode 10 이하 버전에서 문제 되므로 available을 지워도 문제가 될 거 같지는 않다는 생각이 드네요.

**Comment by heejinnn** [comment]
확인했습니다! 그럼 지우는 쪽으로 가도 괜찮을 것 같네요. 찾아주셔서 감사합니다!
