### ISSUE TITLE
🔧 디자인에서 제공된 px 값이 iOS 디바이스에서 작게 보이는 문제 해결을 위한 수정

### ISSUE THREAD

**Issue by heejinnn** [CollaBu/pennyway-client-ios#28]
## 수정 목적

- 디자인팀에서 제공한 px 값이 실제 디바이스에서 작게 나타나는 문제를 해결하기 위함

## 수정 코드

- 추후 수정해야 함

## 할 일 목록
- [x] 포인트와 픽셀 간의 관계에 대한 이해 강화
- [x] 디바이스 별 font size 지정
- [x] 디자인된 size에 비율 곱하기 

### ✏️ 디자인과 개발 se 사이즈의 차이

- 개발 se 사이즈

SE 2, 3세대(4.7인치)
375x667 pt (750x1334 px @2x)

- 디자인한 se 사이즈

SE 1 세대(4인치)
320x568 pt (640x1136 px @2x)

<br/>

### 🔎  문제가 발생한 이유

만약 320x568px 프레임 사이즈에 디자인된 값을 pt로 변환하여 같은 320x568pt 프레임 사이즈에 적용하면 디자인된 값과 비슷하게 나왔을 것이다.  
px를 pt로 변환할 때 ppi를 고려해야한다는 것은 인치당 픽셀 수를 고려하기 위해서다. 해상도를 고려하면 320x568pt는 물리적 사이즈로 640
x1136 px이다. 

변환된 pt 값은 다음과 같은 공식으로 계산된다.

pt = (px/ppi) x 72

여기서 72는 1인치당 포인트 수이다.

이제 주어진 PPI 값을 기반으로 px를 pt로 변환해보자. 예를 들어, px가 100이고 PPI가 326인 경우(se1세대)를 가정한다.

pt = (100/326) × 72

계산을 해보면, 약 22.086pt가 된다.

=> 만약 디자인팀에서 640x1136 px를 기준으로 작업을 하고 320x568 pt 사이즈의 기기에 적용하려고 하면 px를 pt로 변경하는 과정이 필요하다.

하지만 320x568 px를 기준으로 디자인하고 320x568 pt 기기에 적용하는 경우 px를 pt로 변경하지 않아도 비슷하게 나온다는 점,,,,,

<br/>

> ✨결론적으로 px와 pt에 대한 변환 문제로 일어난 문제라기 보다는 디자인된 se size와 개발 se size와의 차이가 있어서 일어난 문제였다고 할 수 있다. 이걸 적절한 비율을 곱해서 해결하고자 한다. 

(xcode 시뮬레이터에서 se가 3세대 밖에 없어서 당연히 같은 크기일거라고 생각한 것이 문제였다....)

<br/>

참고 https://developer.apple.com/design/human-interface-guidelines/layout

**Comment by yanni13** [comment]
디바이스 별로 픽셀값 계산해서 사용할 수 있도록 `customFont`파일에 모듈화 시키는게 좋을거 같습니다.

**Comment by heejinnn** [comment]
https://github.com/jane1choi/TIL/issues/1
여기서 지금 저희 방식대로 정해진 비율만큼 곱해서 사용하더라고요 패딩이랑 뷰 사이즈 등등에 적용해도 문제는 없을 듯 싶네요! 
그래도 더 좋은 방법이 있을 수 있으니 찾아봐주시면 감사하겠습니다!

**Comment by yanni13** [comment]
https://hanulyun.medium.com/swift-iphone-%ED%95%B4%EC%83%81%EB%8F%84%EB%B3%84-%EC%98%A4%ED%86%A0%EB%A0%88%EC%9D%B4%EC%95%84%EC%9B%83%EC%9D%84-%ED%95%98%EB%8A%94-2%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95-5ef1f3726d0d

제가 찾은 블로그 방법이랑 희진님이 올려주신거랑 비슷한거 같네요! 한번 읽어보시고 문제 없으면 그대로 진행해도 괜찮을거 같습니다~

**Comment by heejinnn** [comment]
넵 그럼 기존의 방식대로 진행하도록 하겠습니다!

**Comment by heejinnn** [comment]
신얀님 저희가 임의로 정했던 비율에 문제점이 있을 수 있다고 생각해서 더 찾아봤습니다!

기존에 생각했던 px를 pt로 변환하는 문제도 있었지만 다른 문제가 있었다는 것을 알았습니다,,,, 이슈에 다시 설명해놓았어요!
pt와 px의 차이에 대해 확실하게 모르다보니 이런 문제가 있는지 파악하는 것도 오래걸리네요

하지만 디바이스별 사이즈 차이가 있던 문제도 있어서 이번에 확실하게 디바이스 별 font, 레이아웃 사이즈에 대해 코드로 정리했으니 코드 적용만 하면 이제 진짜로 해결될 것 같습니다 ㅎㅎㅎ 

그래서 이전에 작성한 비율이 se 1세대를 기준으로 달라질 수 있다는 점 양해부탁드립니다! 
오늘 중으로 pr 올리겠습니다~

**Comment by yanni13** [comment]
저도 이 고민을 해봤었는데요, 디자인 해주신 캔버스 사이즈가 SE1세대고, 빌드해서 확인한 디바이스 사이즈가 SE3세대니까 320 -> 375로 바뀌었으니 대략 1.15배 정도 차이나는 부분이 저희가 처음에 얘기했던 부분이라서 따로 고려를 안해봤었어요

근데 오늘 희진님이 얘기해주신 부분에 대해 더 찾아보니 스유에서는 px로 입력해도 자동으로 pt 단위로 적용을 하기 때문에 pt에 일일이 대응하는건 거의 하지 않는 작업이라고 하더라고요

대신 해상도비율에 맞춰 수동작업 해주는 부분에 필요할 거 같은데 이게 새 이슈로 남겨놓은 부분 같아요! 링크로 남겨주신 부분 확인했고 PR 올려주시면 확인하겠습니다~
