### ISSUE TITLE
🐛 메인화면에서 과거 지출내역 조회시 캘린더 상태 관리 문제

### ISSUE THREAD

**Issue by yanni13** [CollaBu/pennyway-client-ios#98]
## 버그 내용
예를 들어 현재 날짜가 7월 4일이고, 메인 화면에서 6월 4일의 지출내역을 클릭했을때 바텀시트가 나온다. 이 바텀시트에서 아무 동작도 하지 않고 닫았을 때 현재날짜인 7월 4일의 지출내역을 보여준다.

### 문제 원인
바텀시트가 올라왔을 때 탭바는 숨겨져야 하고, 시트가 닫겼을 때 메인화면으로 돌아가 다시 탭바가 보이도록 해야 한다.
이과정을` @State private var ishidden = false` 이라는 상태변수로 관리하여 바텀시트가 나오는 뷰일 때, ishidden의 상태를 변경해주고 탭바에 반영한다. 
```swift
        .onChange(of: showSpendingDetailView) { isPresented in
            ishidden = isPresented
            Log.debug("ishidden: \(isPresented)")
        }
...
            .setTabBarVisibility(isHidden: ishidden)
           .id(ishidden)

``` 
그리고 반영된 ishidden의 true/false 값으로 탭바의 여부를 판단하고 전체뷰를 리렌더링 시켜준다.

- 문제는 전체뷰를 리렌더링 시키줄 때 캘린더의 상태까지 새로고침하여 오늘날짜가 7월 4일일 경우 5월 지출내역을 눌러 5월 지출에 대한 바텀시트가 올라왔을때 이 바텀시트를 닫게 되면 다시 7월 내역으로 돌아가게 되며, 5월 내역이 7월에 덮어씌어지는 경우가 발생한다.

## 버그 위치
 - `SpendingManagementMainView`
 - `SpendingDetailSheetView`
 - `SpendingCalenderView`
 - `SpendingCalendarCellView`

## 재현
![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-07-04 at 23 17 54](https://github.com/CollaBu/pennyway-client-ios/assets/122153297/f4534e45-8ae8-421d-97fa-b6b6a8d86bcd)

## 할일
- `.id(ishidden)`을 없애면 위 버그 이슈는 해결되지만, 바텀시트를 닫았을 때 뷰가 리렌더링 되지 않아 메인화면에서 잘 있던 탭바가 없어지는 문제가 발생한다.
- 특정뷰만 `.id(ishidden)` 이 속성을 적용하지 않게 뷰를 분리하면 되지 않을까?라고 생각했지만 SpendingManagementMainView뷰 안에 SpendingCalenderView가 하위뷰로 속해있고, 탭바는 상위뷰인 SpendingManagementMainView에서 관리해야 하기 때문에 사실상 불가능하다.

- 어떻게 해결해야 할 지 감이 안온다 ,, 캘린더의 상태를 유지해버리면 탭바가 없어지고 탭바 상태를 유지하려면 캘린더 상태도 같이 새로고침된다 -.....

**Comment by heejinnn** [comment]
만약 현재 7월이고, 6월에 SpendingManagementMainView -> SpendingDetailSheetView가 나온 후에 다시 SpendingManagementMainView로 돌아가면 캘린더는 7월이고 각 날짜의 지출내역은 6월인 문제인거잖아요!

확인해보니 지출 내역을 가져오는 건 제대로 동작하고 있고, 캘린더의 달을 가져올 때 계속 현재 기준으로 처리하더라고요!

그래서 SpendingCalenderView에서 캘린더의 날짜를 정하는 date 부분만 수정하면 될 것 같아요!

`@State var date: Date = Date()`로 처리하던 로직을 `spendingHistoryViewModel.currentDate` 값으로 초기화해주도록 변경하니까 해결되었어요!


```swift
struct SpendingCalenderView: View {
    @ObservedObject var spendingHistoryViewModel: SpendingHistoryViewModel
    @State private var selectedDate: Date?
    @Binding var showSpendingDetailView: Bool
    @State var date: Date
    @State private var clickedCurrentMonthDates: Date?
   ...
    
//초기화
    init(spendingHistoryViewModel: SpendingHistoryViewModel, showSpendingDetailView: Binding<Bool>, date: Binding<Date>) {
        self.spendingHistoryViewModel = spendingHistoryViewModel
        self._showSpendingDetailView = showSpendingDetailView//바인딩 값이라서 처리해줘야 함
        self._date = State(initialValue: spendingHistoryViewModel.currentDate)
    }

```  
_는 binding이나 state를 초기화할 때 사용해야한다고 하더라고요!
